server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
  
spring:
  application:
    name: Api-gateway
  cloud:
    gateway:
      routes:
      - id: cropdetails
        uri: http://localhost:8095/
        predicates:
        - Path=/api/**
      - id: orders
        uri: http://localhost:8054/
        predicates:
        - Path=/apicart/**
      
      - id: payment
        uri: http://localhost:8083/
        predicates:
        - Path=/payment/**
      
      - id: farmer
        uri: http://localhost:8096/
        predicates:
        - Path=//api/**
      - id: orders
        uri: http://localhost:8099/
        predicates:
        - Path=//api/**
      
        
      